name: '😇 疑问或帮助 Help Wanted'
description: '疑问或需要帮助 | Need help'
title: '[Question] '
labels: '😇 Help Wanted'
body:
  - type: textarea
    attributes:
      label: '🧐 问题描述 | Proposed Solution'
      description: |
        清晰且简洁地描述你遇到的问题。请按照以下的故障排除步骤操作，更新 webui 和 lobe 主题到最新版本。如果问题仍然存在，尝试检查是否有其他插件与之冲突，并提供冲突插件的名称。
        A clear and concise description of what your problem. Please follow the troubleshooting steps below, update the webui and lobe theme to the latest version. If the problem persists, try to check if there is a conflict with other plugins and provide the name of the conflicting plugin.
    validations:
      required: true
  - type: textarea
    attributes:
      label: '📝 补充信息 | Additional Information'
      description: Add any other context about the problem here.
